workflows:
  react-native-ios:
    name: React Native iOS Build
    max_build_duration: 60

    environment:
      node: 18
      xcode: latest

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Recreate iOS folder (FIX)
        script: |
          rm -rf ios
          npx react-native init TempAppTemp --skip-install
          cp -r TempAppTemp/ios ./ios
          rm -rf TempAppTemp

      - name: Install Pods
        script: |
          cd ios
          pod install
          cd ..

      - name: Verify workspace
        script: |
          ls ios

      - name: Build Archive
        script: |
          xcodebuild \
            -workspace ios/TempApp.xcworkspace \
            -scheme TempApp \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/TempApp.xcarchive archive

    artifacts:
      - build/**